### ISSUE TITLE
[FEATURE] 가치관 카테고리 API 개발

### ISSUE THREAD

**Issue by wlaud2000** [Zagabi-LikeLion/BackEnd#10]
# Title

- 가치관 카테고리 API 개발

# TODO

- [x] 카테고리 생성
- [x] 모든 카테고리 조회
- [x] 특정 카테고리 조회
- [x] 카테고리 이름 변경
- [x] 카테고리 삭제

# etc

**Comment by wlaud2000** [comment]
API 개발은 다 완료하였고 인증 인가 부분 개발 완료되면 테스트해서 풀리퀘 올리겠습니다.
개인 리포에서는 테스트 다 완료하였습니다!
