### ISSUE TITLE
[FEATURE] 가치관 변화 기록 API 작성

### ISSUE THREAD

**Issue by Ohwooseok** [Zagabi-LikeLion/BackEnd#12]
# Title

- 가치관 변화 기록 API 작성

# TODO

- [ ] 가치관 변화 기록 생성
- [ ] 가치관 변화 기록 조회
- [ ] 가치관 변화 기록 전체 조회
# etc
