### ISSUE TITLE
[REFACTOR] 가치관, 가치관 기록, 가치관 휴지통 인증 인가 연결

### ISSUE THREAD

**Issue by Ohwooseok** [Zagabi-LikeLion/BackEnd#24]
# Title

- 가치관, 가치관 기록, 가치관 휴지통 인증 인가 연결

# TODO

- [ ] 가치관 인증 인증 인가 연결
- [ ] 가치관 기록 인증 인가 연결
- [ ] 가치관 휴지통 인증 인가 연결

# etc
