### ISSUE TITLE
[FEATURE] 가치관 휴지통 API 개발

### ISSUE THREAD

**Issue by Ohwooseok** [Zagabi-LikeLion/BackEnd#8]
# Title

- 가치관 휴지통 API 개발

# TODO

- [ ] 가치관 휴지통 등록
- [ ] 가치관 휴지통 조회
- [ ] 가치관 휴지통 전체 조회

# etc
